"""empty message

Revision ID: b2601be3bf1e
Revises:
Create Date: 2025-12-17 22:25:12.931927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2601be3bf1e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feat",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("caster", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "material",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "material_component",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "source",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tool",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("tool_type", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weapon_kind",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("weapon_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "weapon_property",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("base_range", sa.Float(), nullable=True),
        sa.Column("max_range", sa.Float(), nullable=True),
        sa.Column("second_hand_dice_name", sa.String(), nullable=True),
        sa.Column("second_hand_dice_count", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "armor",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("armor_type", sa.String(), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("stealth", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("base_class", sa.Integer(), nullable=False),
        sa.Column("modifier", sa.String(length=50), nullable=True),
        sa.Column("max_modifier_bonus", sa.Integer(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "character_class",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("hit_dice_name", sa.String(length=50), nullable=False),
        sa.Column("hit_dice_count", sa.Integer(), nullable=False),
        sa.Column("starting_hits", sa.Integer(), nullable=False),
        sa.Column("hit_modifier", sa.String(), nullable=False),
        sa.Column("next_level_hits", sa.Integer(), nullable=False),
        sa.Column("number_skills", sa.Integer(), nullable=False),
        sa.Column("number_tools", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "feat_increase_modifier",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("feat_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feat_id"], ["feat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feat_required_armor_type",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("feat_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feat_id"], ["feat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feat_required_modifier",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("min_value", sa.Integer(), nullable=False),
        sa.Column("feat_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["feat_id"], ["feat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "race",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("base_speed", sa.Float(), nullable=False),
        sa.Column("speed_description", sa.String(), nullable=False),
        sa.Column("max_age", sa.Integer(), nullable=False),
        sa.Column("age_description", sa.String(), nullable=False),
        sa.Column("creature_type", sa.String(length=50), nullable=False),
        sa.Column("creature_size", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "spell",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("next_level_description", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("school", sa.String(), nullable=False),
        sa.Column("damage_type", sa.String(), nullable=True),
        sa.Column("spell_range", sa.Float(), nullable=False),
        sa.Column("splash", sa.Float(), nullable=True),
        sa.Column("duration_unit", sa.String(), nullable=True),
        sa.Column("duration_count", sa.Integer(), nullable=True),
        sa.Column("casting_time_unit", sa.String(), nullable=False),
        sa.Column("casting_time_count", sa.Integer(), nullable=False),
        sa.Column("concentration", sa.Boolean(), nullable=False),
        sa.Column("ritual", sa.Boolean(), nullable=False),
        sa.Column("verbal_component", sa.Boolean(), nullable=False),
        sa.Column("symbolic_component", sa.Boolean(), nullable=False),
        sa.Column("material_component", sa.Boolean(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tool_utilize",
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("complexity", sa.Integer(), nullable=False),
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tool_id"], ["tool.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weapon",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("damage_dice_name", sa.String(), nullable=False),
        sa.Column("damage_dice_count", sa.Integer(), nullable=False),
        sa.Column("damage_type", sa.String(), nullable=False),
        sa.Column("bonus_damage", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("kind_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kind_id"],
            ["weapon_kind.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "character_subclass",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"],
            ["character_class.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "class_armor_type",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_feature",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "class_level",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("dice_name", sa.String(), nullable=True),
        sa.Column("dice_count", sa.Integer(), nullable=True),
        sa.Column("dice_description", sa.String(), nullable=True),
        sa.Column("number_cantrips_know", sa.Integer(), nullable=True),
        sa.Column("number_spells_know", sa.Integer(), nullable=True),
        sa.Column("number_arcanums_know", sa.Integer(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("points_description", sa.String(), nullable=True),
        sa.Column("bonus_damage", sa.Integer(), nullable=True),
        sa.Column("bonus_damage_description", sa.String(), nullable=True),
        sa.Column("increase_speed", sa.Float(), nullable=True),
        sa.Column("increase_speed_description", sa.String(), nullable=True),
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_primary_modifier",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_saving_throw",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_skill",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "race_feature",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("race_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "race_increase_modifier",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("bonus", sa.Integer(), nullable=False),
        sa.Column("race_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["race_id"], ["race.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_class_tool",
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tool_id"], ["tool.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_class_weapon",
        sa.Column("weapon_id", sa.Uuid(), nullable=False),
        sa.Column("class_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["weapon_id"], ["weapon.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_spell_character_class",
        sa.Column("character_class_id", sa.Uuid(), nullable=False),
        sa.Column("spell_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_class_id"], ["character_class.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["spell.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_spell_material",
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("spell_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"], ["material_component.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["spell.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_weapon_property",
        sa.Column("weapon_id", sa.Uuid(), nullable=False),
        sa.Column("weapon_property_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weapon_id"], ["weapon.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["weapon_property_id"], ["weapon_property.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("weapon_id"),
    )
    op.create_table(
        "spell_saving_throw",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("spell_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["spell.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subrace",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("race_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["race.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "class_level_spell_slot",
        sa.Column("level_1", sa.Integer(), nullable=False),
        sa.Column("level_2", sa.Integer(), nullable=False),
        sa.Column("level_3", sa.Integer(), nullable=False),
        sa.Column("level_4", sa.Integer(), nullable=False),
        sa.Column("level_5", sa.Integer(), nullable=False),
        sa.Column("level_6", sa.Integer(), nullable=False),
        sa.Column("level_7", sa.Integer(), nullable=False),
        sa.Column("level_8", sa.Integer(), nullable=False),
        sa.Column("level_9", sa.Integer(), nullable=False),
        sa.Column("class_level_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_level_id"], ["class_level.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rel_spell_character_subclass",
        sa.Column("character_subclass_id", sa.Uuid(), nullable=False),
        sa.Column("spell_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_subclass_id"],
            ["character_subclass.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["spell_id"], ["spell.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subclass_feature",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("name_in_english", sa.String(length=50), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("character_subclass_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_subclass_id"],
            ["character_subclass.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "subrace_feature",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("subrace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subrace_id"], ["subrace.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subrace_increase_modifier",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("bonus", sa.Integer(), nullable=False),
        sa.Column("subrace_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subrace_id"], ["subrace.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subrace_increase_modifier")
    op.drop_table("subrace_feature")
    op.drop_table("subclass_feature")
    op.drop_table("rel_spell_character_subclass")
    op.drop_table("class_level_spell_slot")
    op.drop_table("subrace")
    op.drop_table("spell_saving_throw")
    op.drop_table("rel_weapon_property")
    op.drop_table("rel_spell_material")
    op.drop_table("rel_spell_character_class")
    op.drop_table("rel_class_weapon")
    op.drop_table("rel_class_tool")
    op.drop_table("race_increase_modifier")
    op.drop_table("race_feature")
    op.drop_table("class_skill")
    op.drop_table("class_saving_throw")
    op.drop_table("class_primary_modifier")
    op.drop_table("class_level")
    op.drop_table("class_feature")
    op.drop_table("class_armor_type")
    op.drop_table("character_subclass")
    op.drop_table("weapon")
    op.drop_table("tool_utilize")
    op.drop_table("spell")
    op.drop_table("race")
    op.drop_table("feat_required_modifier")
    op.drop_table("feat_required_armor_type")
    op.drop_table("feat_increase_modifier")
    op.drop_table("character_class")
    op.drop_table("armor")
    op.drop_table("weapon_property")
    op.drop_table("weapon_kind")
    op.drop_table("user")
    op.drop_table("tool")
    op.drop_table("source")
    op.drop_table("material_component")
    op.drop_table("material")
    op.drop_table("feat")
    # ### end Alembic commands ###
